version: "3.8"
services:
  frontend:
    image: react_frontend
    container_name: react_frontend
    build:
      context: ./inventory-frontend
      dockerfile: Dockerfile
    volumes:
       - ./inventory-frontend:/app
    ports:
      - 3000:3000
    network_mode: bridge  

  backend_product:
    image: backend
    container_name: backend_inventory
    build:
      context: ./inventory
    volumes:
      - ./inventory:/code
    ports:
      - 8000:8000
    network_mode: bridge  
  backend_payment:
    image: backend_payment
    container_name: backend_payment
    build:
      context: ./payment
    volumes:
      - ./payment:/code
    ports:
      - 8001:8001
    network_mode: bridge  