version: "3.9"
services:
  frontend:
    image: react_frontend
    container_name: react_frontend
    depends_on:
      - backend_inventory
      - backend_payment
    build:
      context: ./inventory-frontend
    volumes:
      - ./inventory-frontend:/app
    ports:
      - 3000:3000
  backend_inventory:
    image: backend
    container_name: backend_inventory
    build:
      context: ./inventory
    volumes:
      - ./inventory:/code
    ports:
      - 8000:8000
  backend_payment:
    image: backend_payment
    container_name: backend_payment
    build:
      context: ./payment
    volumes:
      - ./payment:/code
    ports:
      - 8001:8001
